import { Dispatch, SetStateAction } from "react";
import { PlusCircleIcon } from "@heroicons/react/outline";

import { ROUNDED } from "../design";
import Button from "./Button";
import TextInput from "./TextInput";
import Autocomplete from "./Autocomplete";
import { Column } from "../../types";
import NumberInput from "./NumberInput";
import Checkbox from "./Checkbox";

interface RowsProps {
  initial_state: Column[];
  state: Column[][];
  setState: Dispatch<SetStateAction<any[]>>;
}

const Rows = ({ initial_state, setState, state }: RowsProps) => {
  return (
    <>
      {state.map((row, row_index) => (
        <div key={row_index} className="w-full flex justify-between my-1">
          {row &&
            row.map((col, col_index) => (
              <div key={col_index}>
                {col.autocomplete && col.collection && (
                  <Autocomplete
                    collection={col.collection}
                    placeholder={col.name}
                    displayValue={col.field}
                    value={col.value}
                    setSelected={(value) => {
                      setState(
                        state.map((r, i) => {
                          if (row_index === i)
                            r = r.map((c, j) => {
                              if (c.index) c.value = String(row_index + 1);
                              if (col_index === j && c.autocomplete)
                                c.value = value[col.field];
                              return c;
                            });
                          return r;
                        })
                      );
                    }}
                  />
                )}
                {!col.autocomplete && (
                  <>
                    {col.type === "checkbox" && (
                      <Checkbox
                        checked={col.value ? true : false}
                        label={col.name}
                        readOnly={col.index || col.autogenerated}
                        onChange={(event) =>
                          setState(
                            state.map((r, i) => {
                              if (row_index === i)
                                r = r.map((c, j) => {
                                  if (c.index) c.value = String(row_index + 1);
                                  if (col_index === j)
                                    c.value = event.target.checked;
                                  return c;
                                });
                              return r;
                            })
                          )
                        }
                      />
                    )}
                    {col.type === "number" && (
                      <NumberInput
                        placeholder={col.name}
                        value={col.value}
                        readOnly={col.index}
                        onChange={(event) =>
                          setState(
                            state.map((r, i) => {
                              if (row_index === i)
                                r = r.map((c, j) => {
                                  if (c.index) c.value = String(row_index + 1);
                                  if (col_index === j)
                                    c.value = event.target.value.toUpperCase();
                                  return c;
                                });
                              return r;
                            })
                          )
                        }
                        type={col.type}
                      />
                    )}
                    {(!col.type || col.type === "text") && (
                      <TextInput
                        placeholder={col.name}
                        value={col.value}
                        readOnly={col.index}
                        onChange={(event) =>
                          setState(
                            state.map((r, i) => {
                              if (row_index === i)
                                r = r.map((c, j) => {
                                  if (c.index) c.value = String(row_index + 1);
                                  if (col_index === j)
                                    c.value = event.target.value.toUpperCase();
                                  return c;
                                });
                              return r;
                            })
                          )
                        }
                        type={col.type}
                        size={col.size}
                      />
                    )}
                  </>
                )}
              </div>
            ))}
        </div>
      ))}
      <div
        onClick={() =>
          setState((prev) => {
            let newstate = prev;
            newstate = [...prev, initial_state];
            return newstate;
          })
        }
        className={`cursor-pointer w-full flex justify-center text-white bg-primary ${ROUNDED} mt-2 mb-1`}
      >
        <Button type="button">
          <PlusCircleIcon className="h-5 w-5 inline" aria-hidden="true" />
        </Button>
      </div>
    </>
  );
};

export default Rows;
